SecretSanta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'), name='app')
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app'


urlpatterns = [
    #маршрутизация логина
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),

    # форма
    path('form/<int:id>', views.form, name='form'),
    path('form/success', views.form_submit, name='form_submit'),

    # организация
    path('', views.index, name='index'),
    path('group/<int:id>', views.group_detail, name='group_detail'),
    path('finish/<int:id>', views.finish, name='finish'),

    # CRUD
    path('<object>/new', views.new, name='new'),
    path('<object>/<int:id>/edit', views.edit, name='edit'),
    path('<object>/<int:group_id>/<int:id>/delete', views.delete, name='delete'),
]

app/templates/components/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Secret-Santa</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <img src="{% static 'SecretSanta/img/Black Gold Bold Modern 3D Happy New Year Card Landscape (1920 × 760 пикс.).png' %}" alt=""
    style="width: 2000px; height: 500px; ">
    {% include 'components/navbar.html' %}

    <div class="body">
        {% block body %}

        {% endblock %}
    </div>
    
    {% include 'components/footer.html' %}
</body>
</html>

app/templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <a class="navbar-brand" href="{% url 'app:index' %}">Тайный санта.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:index' %}">Группы</a>
                </li>
                <li class="nav-item">

                </li>
            </ul>
        {% endif %}

        <a class="nav-link navbar-dark bg-dark" href="{% url 'app:logout' %}">Выйти</a>

    </div>
</nav>