SecretSanta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'), name='app')
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app'


urlpatterns = [
    #маршрутизация логина
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),

    # форма
    path('form/<int:id>', views.form, name='form'),
    path('form/success', views.form_submit, name='form_submit'),

    # организация
    path('', views.index, name='index'),
    path('group/<int:id>', views.group_detail, name='group_detail'),
    path('finish/<int:id>', views.finish, name='finish'),

    # CRUD
    path('<object>/new', views.new, name='new'),
    path('<object>/<int:id>/edit', views.edit, name='edit'),
    path('<object>/<int:group_id>/<int:id>/delete', views.delete, name='delete'),
]

app/templates/views/form.html
{% extends 'components/base.html' %}

{% block body %}
    <h1 class="display-3 title" style="margin-bottom: 50px;">{{ group.name }}</h1>

    <form action="" method="post">
        {% csrf_token %}

        <div style="width: 400px;">
            <div class="row row-margin">
                <label for="name" class="col-6">Имя: </label>
                <input class="text-input col-6" type="text" name="name" placeholder="Required" required>
            </div>

            <div class="row row-margin">
                <label for="email" class="col-6">Email: </label>
                <input class="text-input col-6" type="email" name="email" placeholder="Required" required>
            </div>

            {% for field in fields %}
                <div class="row row-margin">
                    <label class="col-6" for="field-{{ field.id }}">{{ field.name }}</label>
                    <input class="text-input col-6" type="text" name="field-{{ field.id }}"
                            {{ field.is_required|yesno:'required placeholder=Required,' }}>
                </div>
            {% endfor %}

            <div>
                <button class="btn btn-info" style="margin: auto;">Отправить</button>
            </div>
        </div>

    </form>

{% endblock %}

app/templates/views/form_submit.html
{% extends 'components/base.html' %}

{% block body %}
    <h1>Форма успешно отправлена</h1>
    <p>Вы получите электронное письмо с назначенным вам человеком, когда все закончат его</p>

{% endblock %}

app/templates/views/group_detail.html
{% extends 'components/base.html' %}

{% block body %}
    <h1 class="display-3 title">{{ group.name }}</h1>
    <a class="btn btn-success float-right new-button" href="{% url 'app:form' group.id %}">Перейти к форме</a>

    <div class="row group-desc-body">
        <div class="col-6">
            <h3 class="display-4">Поля формы</h3>
            <p style="margin-top: 25px;">Имя</p>
            <p style="margin-top: 25px;">Email</p>

            <div style="width: 65%;">
                {% for field in fields %}
                <div class="row" style="margin-top: 25px;">
                    <span class="col-8">{{ field.name }}</span>

                    <div class="col-4">
                        <a class="btn btn-danger" href="{% url 'app:delete' 'field' group.id field.id %}">Удалить</a>
                        <a class="btn btn-secondary" href="{% url 'app:edit' 'field' field.id %}">Редактировать</a>
                    </div>
                </div>
            {% endfor %}
            </div>

            <a style="margin-top: 25px;" class="btn btn-info" href="{% url 'app:new' 'field' %}?group={{ group.id }}">Создать новое поле</a>
        </div>

        <div class="col-6">
            <h3 class="display-4">Заявки</h3>
            {% if simple_users.count == 0 %}
                <p>Заявок пока нет.</p>
            {% endif %}

            <div style="width: 65%;">
                {% for simple_user in simple_users %}
                    <div style="width: 100%; margin-top: 25px;" class="row">
                        <div class="col-8">{{ simple_user.name }} - {{ simple_user.email }}</div>
                        <div class="col-1"></div>-
                        <a class="btn btn-danger col-3" style=" height:40px;"
                           href="{% url 'app:delete' 'simpleuser' group.id simple_user.id %}">удалить</a>
                    </div>
                {% endfor %}
            </div>

            <a style="margin-top: 15px; font-size:1.5em;" class="btn btn-info" href="{% url 'app:finish' group.id %}">Закончить</a>
        </div>
    </div>

{% endblock %}

app/templates/views/index.html
{% extends 'components/base.html' %}

{% block body %}

    <h1 class="display-3 title">Группы</h1>
    <a class="btn btn-info float-right new-button" href="{% url 'app:new' 'group' %}">Создать игру</a>

    <div>
        {% for group in groups %}
            <div class="card float-left">
                <div class="card-body">
                    <h5 class="card-title">{{ group.name }}</h5>
                    <div style="margin-top: 20px;">
                        <a class="btn btn-primary" href="{% url 'app:group_detail' group.id %}">ПОДРОБНО</a>
                        <a class="btn btn-danger" href="{% url 'app:delete' 'group' group.id group.id %}">УДАЛИТЬ</a>
                        <a class="btn btn-secondary" href="{% url 'app:edit' 'group' group.id %}">ИЗМЕНТЬ</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

app/templates/views/new.html
{% extends 'components/base.html' %}

{% block body %}
    <!--
        Layout:
          - ability to create new group
     -->
    <h1 class="display-3 title" style="margin-bottom: 50px;">{{ model_object|yesno:'Edit,New' }} {{ object|title }}</h1>

    <form action="" method="POST">
        {% csrf_token %}

        {% if object == 'field' %}
            <input type="hidden" name="group_id" value={{ group.id }}>
        {% endif %}

        <input type="hidden" name="owner_id" value={{ user.id }}>

        <label for="name">Имя: </label>
        <input class="text-input" type="text" value="{{ model_object.name }}" name="name" placeholder="{{ object|title }} Name">


        {% if object == 'field' %}
            <br>
            <label for="is_required">Обязательно</label>
            <input type="checkbox" name="is_required" checked="{{ model_object.is_required|yesno:'checked,' }}">
        {% endif %}
        <br>
        <button class="btn btn-info">Сохранить</button>
    </form>

{% endblock %}